"""Registry of all domain rules used by the review agents."""

from rules.rule_models import Rule, Severity

SECURITY_RULES: list[Rule] = [
    Rule(
        id="SEC-001",
        severity=Severity.CRITICAL,
        category="security",
        description="Hardcoded password, token, or secret in source code",
        pattern=r"(?i)(password|passwd|pwd|secret|token|api_key|apikey|auth_token)\s*=\s*['\"][^'\"]{3,}['\"]",
        fix_hint="Use Airflow Connections or Vault-injected secrets.",
    ),
    Rule(
        id="SEC-008",
        severity=Severity.HIGH,
        category="security",
        description="subprocess with shell=True can allow command injection",
        pattern=r"subprocess\.(run|call|Popen|check_output)\s*\([^)]*shell\s*=\s*True",
        fix_hint="Pass command args as a list and use shell=False.",
    ),
    Rule(
        id="SEC-014",
        severity=Severity.HIGH,
        category="security",
        description="AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True exposes sensitive config",
        pattern=r"AIRFLOW__WEBSERVER__EXPOSE_CONFIG\s*=\s*['\"]?[Tt]rue",
        fix_hint="Disable EXPOSE_CONFIG in production environments.",
    ),
    Rule(
        id="SEC-015",
        severity=Severity.HIGH,
        category="security",
        description="BashOperator command built from dag_run.conf without validation",
        pattern=r"bash_command\s*=\s*['\"].*\{\{.*dag_run\.conf",
        fix_hint="Validate/sanitize dag_run.conf values before shell usage.",
    ),
]

AIRFLOW_RULES: list[Rule] = [
    Rule(
        id="AF-005",
        severity=Severity.CRITICAL,
        category="airflow",
        description="start_date uses datetime.now()/utcnow() and becomes non-deterministic",
        pattern=r"start_date\s*=\s*(datetime\.now|datetime\.utcnow)\s*\(",
        fix_hint="Use static pendulum.datetime(..., tz='UTC').",
    ),
    Rule(
        id="AF-006",
        severity=Severity.HIGH,
        category="airflow",
        description="catchup=True can create a large backlog without explicit controls",
        pattern=r"catchup\s*=\s*True",
        fix_hint="Set catchup explicitly and control max_active_runs.",
    ),
    Rule(
        id="AF-010",
        severity=Severity.MEDIUM,
        category="airflow",
        description="execution_date usage is deprecated in Airflow 2.x",
        pattern=r"\bexecution_date\b",
        fix_hint="Use logical_date or data_interval_start/end.",
    ),
    Rule(
        id="AF-012",
        severity=Severity.MEDIUM,
        category="airflow",
        description="Sensor in mode='poke' can hold workers for long waits",
        pattern=r"mode\s*=\s*['\"]poke['\"]",
        fix_hint="Use mode='reschedule' for long waits.",
    ),
    Rule(
        id="AF-013",
        severity=Severity.MEDIUM,
        category="airflow",
        description="ExternalTaskSensor without execution_delta/date_fn may never match",
        pattern=r"ExternalTaskSensor\s*\(",
        fix_hint="Set execution_delta or execution_date_fn explicitly.",
    ),
    Rule(
        id="AF-014",
        severity=Severity.HIGH,
        category="airflow",
        description="Deprecated Airflow 1.x import path",
        pattern=r"from airflow\.(operators|sensors|hooks)\.(bash_operator|python_operator|http_sensor|s3_hook|postgres_hook)",
        fix_hint="Migrate to Airflow 2.x provider/module imports.",
    ),
    Rule(
        id="AF-015",
        severity=Severity.HIGH,
        category="airflow",
        description="SubDagOperator removed in Airflow 2.x",
        pattern=r"\bSubDagOperator\b",
        fix_hint="Replace with TaskGroup.",
    ),
    Rule(
        id="AF-016",
        severity=Severity.LOW,
        category="airflow",
        description="DummyOperator renamed to EmptyOperator",
        pattern=r"\bDummyOperator\b",
        fix_hint="Use airflow.operators.empty.EmptyOperator.",
    ),
    Rule(
        id="AF-017",
        severity=Severity.HIGH,
        category="airflow",
        description="provide_context=True removed in Airflow 2.0",
        pattern=r"provide_context\s*=\s*True",
        fix_hint="Remove provide_context argument.",
    ),
    Rule(
        id="AF-018",
        severity=Severity.MEDIUM,
        category="airflow",
        description="airflow.utils.dates is deprecated",
        pattern=r"from airflow\.utils\.dates import|airflow\.utils\.dates\.",
        fix_hint="Use pendulum APIs instead.",
    ),
    Rule(
        id="AF-026",
        severity=Severity.MEDIUM,
        category="airflow",
        description="Heavy operator used without pool assignment",
        pattern=r"(SparkSubmitOperator|EmrAddStepsOperator)\s*\(",
        fix_hint="Assign a bounded pool for heavy operators.",
    ),
    Rule(
        id="AF-027",
        severity=Severity.LOW,
        category="airflow",
        description="dagrun_timeout not set",
        pattern=r"DAG\s*\(",
        fix_hint="Set dagrun_timeout for runaway dagrun protection.",
    ),
]

PYTHON_RULES: list[Rule] = [
    Rule(
        id="PY-003",
        severity=Severity.HIGH,
        category="python",
        description="Mutable default argument can leak state across calls",
        pattern=r"def\s+\w+\s*\([^)]*=\s*(\[\]|\{\}|set\(\))",
        fix_hint="Use None sentinel and initialize inside function.",
    ),
    Rule(
        id="PY-005",
        severity=Severity.LOW,
        category="python",
        description="print() in library/runtime code should use logging",
        pattern=r"\bprint\s*\(",
        fix_hint="Use logging.getLogger(__name__).<level>(...).",
    ),
    Rule(
        id="PY-009",
        severity=Severity.HIGH,
        category="python",
        description="Exception swallowed with pass/return None/False",
        pattern=r"except\s+[\w\s,()]+:\s*\n\s*(pass|return\s+None|return\s+False)",
        fix_hint="Log with traceback and re-raise or handle explicitly.",
    ),
    Rule(
        id="PY-010",
        severity=Severity.HIGH,
        category="python",
        description="Bare except catches system-level exceptions and hides root cause",
        pattern=r"except\s*:\s*$",
        fix_hint="Catch explicit exception types and preserve traceback context.",
    ),
    Rule(
        id="PY-011",
        severity=Severity.MEDIUM,
        category="python",
        description="Resource acquisition without context manager or finally cleanup",
        pattern=r"(open\s*\(|\.connect\s*\(|\.cursor\s*\()",
        fix_hint="Use context managers or explicit try/finally cleanup for resources.",
    ),
    Rule(
        id="PY-012",
        severity=Severity.MEDIUM,
        category="python",
        description="assert used in production control flow or validation",
        pattern=r"^\s*assert\s+",
        fix_hint="Use explicit if/raise for runtime validation rather than assert.",
    ),
]

TERADATA_RULES: list[Rule] = [
    Rule(id="TD-001", severity=Severity.HIGH, category="teradata",
         description="Teradata INSERT without MERGE/UPSERT — duplicate rows on retry",
         pattern=r"(?i)\bINSERT\s+INTO\b(?!.*\bMERGE\b)",
         fix_hint="Use MERGE INTO ... USING ... ON ... for idempotent writes."),
    Rule(id="TD-002", severity=Severity.HIGH, category="teradata",
         description="teradatasql.connect() without context manager or finally close",
         pattern=r"teradatasql\.connect\s*\(",
         fix_hint="Wrap in try/finally: conn.close()."),
    Rule(id="TD-003", severity=Severity.MEDIUM, category="teradata",
         description="Teradata cursor not closed in finally block",
         pattern=r"\.cursor\s*\(\s*\)",
         fix_hint="Use 'with conn.cursor() as cur:' or close in finally."),
    Rule(id="TD-004", severity=Severity.CRITICAL, category="teradata",
         description="f-string or % formatting in Teradata SQL — injection risk",
         pattern=r"(?:cursor|cur)\.execute\s*\(\s*(?:f['\"]|['\"].*%)",
         fix_hint="Use parameterized queries: cursor.execute(sql, (param1, param2))."),
    Rule(id="TD-005", severity=Severity.HIGH, category="teradata",
         description="Staging table not truncated before load — double-load on retry",
         pattern=r"(?i)\bINSERT\s+INTO\s+\w*stag",
         fix_hint="Add DELETE FROM staging_table at task start before any INSERT."),
]

DATASET_RULES: list[Rule] = [
    Rule(id="DS-001", severity=Severity.CRITICAL, category="dataset",
         description="Dataset URI in consumer does not match any producer outlet URI",
         pattern=r"schedule\s*=\s*\[.*Dataset\s*\(",
         fix_hint="Consumer Dataset URI must exactly match producer outlets=[Dataset(uri)]."),
    Rule(id="DS-002", severity=Severity.HIGH, category="dataset",
         description="Dataset outlet fires before write is verified complete",
         pattern=r"outlets\s*=\s*\[.*Dataset",
         fix_hint="Outlet task must only run after all writes are confirmed complete."),
    Rule(id="DS-003", severity=Severity.HIGH, category="dataset",
         description="Multiple DAGs producing same Dataset URI — consumer triggered multiple times",
         pattern=r"outlets\s*=\s*\[.*Dataset\s*\(['\"]([^'\"]+)['\"]",
         fix_hint="Ensure consumer is idempotent — it will be triggered once per producer run."),
    Rule(id="DS-004", severity=Severity.MEDIUM, category="dataset",
         description="Dataset URI does not follow s3://{bucket}/{project}/{stage}/{entity} convention",
         pattern=r"Dataset\s*\(\s*['\"](?!s3://)",
         fix_hint="Use s3:// URIs for Dataset scheduling to tie datasets to actual S3 locations."),
    Rule(id="DS-005", severity=Severity.MEDIUM, category="dataset",
         description="No catchup strategy documented for missed Dataset events",
         pattern=r"schedule\s*=\s*\[.*Dataset",
         fix_hint="Document reprocessing strategy — Dataset-triggered DAGs do not backfill."),
]

ALL_RULES: dict[str, list[Rule]] = {
    "security": SECURITY_RULES,
    "airflow": AIRFLOW_RULES,
    "python": PYTHON_RULES,
    "teradata": TERADATA_RULES,
    "dataset": DATASET_RULES,
}
